### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_recording'

### ISSUE THREAD

**Issue by azzurras18** [openai/gym-recording#9]
Hi, I need to record my  Gym environment so I've put on my code:

import gym
from gym_recording.wrappers import TraceRecordingWrapper

When I run my code, I get: ModuleNotFoundError: No module named 'gym_recording'

I've done from prompt: pip install gym_recording 

Everything goes well but when I run the code, I still get the same error.

What should I do?

**Comment by snigdhkarki** [comment]
I am facing the same problem what did you do?
